format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

command_timeout = 1000

[username]
show_always = true

[directory]
style = "blue"
truncation_length = 5

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[!](bold red)"

[git_branch]
format = "[$branch]($style)"

[git_status]
disabled = true

